---

- name: install software for generating manuscripts
  yum: name={{ item }}
       state=present
  with_items:
    - texlive
    - texlive-latex
    - texlive-xetex
    - texlive-collection-latex
    - texlive-collection-latexrecommended
    - texlive-xetex-def
    - texlive-collection-xetex
    - pandoc
    - pandoc-citeproc
    - pandoc-pdf
