---

- name: base install of scientific software and libraries
  hosts: all
  
  roles:
    - system_update
    - epel
    - editors
    - terminal_tools
    - development_tools
    - python
    - ruby
    - java
    - r
    - figure_preparation_tools
    - manuscript_preparation_tools

- name: install a desktop on top of the base system
  hosts: desktops
  
  roles:
    - desktop
    - gui_software
